<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="sabir" failures="1" tests="3" name="user-john" time="7.927" errors="0" timestamp="2024-08-08T21:32:34 CEST">
  <testcase classname="com.sabir.tests.vendorportal.VendorPortalTest" name="loginTest" time="0.751"/>
  <testcase classname="com.sabir.tests.vendorportal.VendorPortalTest" name="dashboardTest" time="3.032">
    <failure type="java.lang.AssertionError" message="expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [0]
at com.sabir.tests.vendorportal.VendorPortalTest.dashboardTest(VendorPortalTest.java:51)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- dashboardTest -->
  <testcase classname="com.sabir.tests.vendorportal.VendorPortalTest" name="logoutTest" time="0.0">
    <skipped/>
  </testcase> <!-- logoutTest -->
</testsuite> <!-- user-john -->
